# Generated by Django 2.1.5 on 2019-03-06 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190306_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 19, 4, 27, 239480), verbose_name='date puplished:'),
        ),
    ]
