# Generated by Django 2.1.5 on 2019-03-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190306_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
